import React from 'react';
import { 
  FileText, 
  Download, 
  Filter, 
  Calendar,
  CheckCircle2,
  Clock,
  AlertCircle,
  MoreVertical,
  Search,
  ArrowUpRight,
  FileSearch,
  ShieldAlert,
  History
} from 'lucide-react';
import { motion } from 'motion/react';
import { cn } from '../../utils';

export const Reports: React.FC = () => {
  const reports = [
    { id: 'REP-001', name: 'Monthly Fraud Summary - Feb 2024', type: 'Executive', date: '2024-03-01', status: 'COMPLETED', size: '2.4 MB', priority: 'HIGH' },
    { id: 'REP-002', name: 'High-Risk Merchant Audit', type: 'Technical', date: '2024-02-28', status: 'COMPLETED', size: '1.8 MB', priority: 'MEDIUM' },
    { id: 'REP-003', name: 'Cross-Border Transaction Analysis', type: 'Intelligence', date: '2024-02-25', status: 'PENDING', size: '-', priority: 'HIGH' },
    { id: 'REP-004', name: 'Agent Performance Metrics Q1', type: 'System', date: '2024-02-20', status: 'COMPLETED', size: '4.2 MB', priority: 'LOW' },
    { id: 'REP-005', name: 'SAR Filing Batch #42', type: 'Legal', date: '2024-02-15', status: 'FAILED', size: '-', priority: 'CRITICAL' },
  ];

  const container = {
    hidden: { opacity: 0 },
    show: {
      opacity: 1,
      transition: {
        staggerChildren: 0.1
      }
    }
  };

  const item = {
    hidden: { opacity: 0, y: 20 },
    show: { opacity: 1, y: 0 }
  };

  return (
    <motion.div 
      variants={container}
      initial="hidden"
      animate="show"
      className="p-10 space-y-12 max-w-[1600px] mx-auto"
    >
      {/* Editorial Header */}
      <motion.div variants={item} className="relative">
        <div className="absolute -left-10 top-0 bottom-0 w-1 bg-primary/20" />
        <div className="flex justify-between items-end">
          <div>
            <div className="flex items-center gap-2 mb-2">
              <span className="text-[10px] font-black uppercase tracking-[0.3em] text-primary">System Integrity</span>
              <div className="h-px w-12 bg-primary/30" />
            </div>
            <h1 className="text-8xl font-black tracking-tighter leading-[0.8] mb-4">
              REPORTS <span className="text-foreground/10">&</span> <br />
              <span className="text-primary">AUDITS</span>
            </h1>
            <p className="text-foreground/40 text-lg font-medium max-w-xl leading-relaxed">
              Legal-grade documentation, compliance logs, and system transparency reports generated by Sentinel Intelligence.
            </p>
          </div>
          <div className="flex flex-col items-end gap-4">
            <div className="flex gap-2">
              <div className="px-4 py-2 bg-surface border border-border rounded-xl flex items-center gap-3">
                <History size={16} className="text-primary" />
                <span className="text-xs font-bold uppercase tracking-widest">Last Audit: 2h ago</span>
              </div>
            </div>
            <button className="group relative px-8 py-4 bg-primary text-white font-black rounded-2xl overflow-hidden transition-all hover:scale-105 active:scale-95 shadow-[0_20px_40px_rgba(0,122,255,0.3)]">
              <div className="absolute inset-0 bg-white/20 translate-y-full group-hover:translate-y-0 transition-transform duration-500" />
              <div className="relative flex items-center gap-3">
                <FileSearch size={20} />
                <span className="uppercase tracking-widest text-sm">Generate Intelligence Report</span>
              </div>
            </button>
          </div>
        </div>
      </motion.div>

      {/* Hardware Stats */}
      <motion.div variants={item} className="grid grid-cols-4 gap-6">
        {[
          { label: 'Total Archives', value: '1,248', icon: FileText, color: 'text-primary', trend: '+12%' },
          { label: 'Verified Logs', value: '1,182', icon: CheckCircle2, color: 'text-success', trend: '98.2%' },
          { label: 'Processing', value: '04', icon: Clock, color: 'text-warning', trend: 'Active' },
          { label: 'Critical Alerts', value: '02', icon: ShieldAlert, color: 'text-danger', trend: 'Immediate' },
        ].map((stat, i) => (
          <div key={i} className="group relative p-8 bg-surface/40 backdrop-blur-xl border border-border rounded-[2.5rem] overflow-hidden transition-all hover:bg-surface/60">
            <div className="absolute top-0 right-0 p-6 opacity-10 group-hover:opacity-20 transition-opacity">
              <stat.icon size={80} />
            </div>
            <div className="relative z-10">
              <div className="flex items-center justify-between mb-6">
                <div className={cn("p-3 rounded-2xl bg-background border border-border", stat.color)}>
                  <stat.icon size={24} />
                </div>
                <span className={cn("text-[10px] font-black uppercase tracking-widest px-3 py-1 rounded-full bg-background border border-border", stat.color)}>
                  {stat.trend}
                </span>
              </div>
              <p className="text-[11px] font-black text-foreground/30 uppercase tracking-[0.2em] mb-1">{stat.label}</p>
              <p className="text-5xl font-black tracking-tighter">{stat.value}</p>
            </div>
          </div>
        ))}
      </motion.div>

      {/* Technical Data Grid */}
      <motion.div variants={item} className="bg-surface/40 backdrop-blur-xl border border-border rounded-[3rem] overflow-hidden shadow-2xl">
        <div className="p-8 border-b border-border flex items-center justify-between bg-surface/20">
          <div className="flex items-center gap-6">
            <h3 className="text-xl font-black tracking-tight">ARCHIVE EXPLORER</h3>
            <div className="h-8 w-px bg-border" />
            <div className="flex items-center gap-4">
              <div className="relative group">
                <Search className="absolute left-4 top-1/2 -translate-y-1/2 text-foreground/20 group-focus-within:text-primary transition-colors" size={18} />
                <input 
                  type="text" 
                  placeholder="Filter by ID, Name, or Type..." 
                  className="bg-background/50 border border-border rounded-2xl pl-12 pr-6 py-3 text-sm w-80 focus:outline-none focus:ring-2 focus:ring-primary/20 transition-all"
                />
              </div>
              <button className="flex items-center gap-2 px-5 py-3 bg-background/50 border border-border rounded-2xl text-[10px] font-black uppercase tracking-widest hover:bg-surface transition-colors">
                <Filter size={14} className="text-primary" />
                Advanced Filters
              </button>
            </div>
          </div>
          <button className="flex items-center gap-2 px-5 py-3 bg-primary/10 text-primary border border-primary/20 rounded-2xl text-[10px] font-black uppercase tracking-widest hover:bg-primary/20 transition-colors">
            <Calendar size={14} />
            Temporal Range
          </button>
        </div>

        <div className="overflow-x-auto">
          <table className="w-full text-left border-collapse">
            <thead>
              <tr className="bg-surface/30 text-[10px] font-black text-foreground/30 uppercase tracking-[0.2em]">
                <th className="px-8 py-6 border-b border-border">Reference ID</th>
                <th className="px-8 py-6 border-b border-border">Documentation Name</th>
                <th className="px-8 py-6 border-b border-border">Classification</th>
                <th className="px-8 py-6 border-b border-border">Timestamp</th>
                <th className="px-8 py-6 border-b border-border">Integrity</th>
                <th className="px-8 py-6 border-b border-border">Payload</th>
                <th className="px-8 py-6 border-b border-border text-right">Actions</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-border/30">
              {reports.map((report) => (
                <tr key={report.id} className="hover:bg-primary/[0.02] transition-colors group cursor-pointer">
                  <td className="px-8 py-6">
                    <div className="flex items-center gap-3">
                      <div className="w-2 h-2 rounded-full bg-primary/40 group-hover:bg-primary transition-colors" />
                      <span className="text-xs font-mono font-black text-primary/60 group-hover:text-primary transition-colors">{report.id}</span>
                    </div>
                  </td>
                  <td className="px-8 py-6">
                    <div className="flex flex-col">
                      <span className="text-sm font-bold group-hover:text-primary transition-colors">{report.name}</span>
                      <span className={cn(
                        "text-[9px] font-black uppercase tracking-widest mt-1",
                        report.priority === 'CRITICAL' ? 'text-danger' : 
                        report.priority === 'HIGH' ? 'text-warning' : 'text-foreground/30'
                      )}>
                        Priority: {report.priority}
                      </span>
                    </div>
                  </td>
                  <td className="px-8 py-6">
                    <span className="px-3 py-1 rounded-lg bg-background border border-border text-[10px] font-black uppercase tracking-widest">
                      {report.type}
                    </span>
                  </td>
                  <td className="px-8 py-6 text-xs font-medium text-foreground/40">{report.date}</td>
                  <td className="px-8 py-6">
                    <div className="flex items-center gap-3">
                      <div className={cn(
                        "w-1.5 h-1.5 rounded-full",
                        report.status === 'COMPLETED' ? 'bg-success shadow-[0_0_10px_rgba(52,199,89,0.5)]' : 
                        report.status === 'PENDING' ? 'bg-warning animate-pulse' : 'bg-danger shadow-[0_0_10px_rgba(255,59,48,0.5)]'
                      )} />
                      <span className={cn(
                        "text-[10px] font-black uppercase tracking-widest",
                        report.status === 'COMPLETED' ? 'text-success' : 
                        report.status === 'PENDING' ? 'text-warning' : 'text-danger'
                      )}>
                        {report.status}
                      </span>
                    </div>
                  </td>
                  <td className="px-8 py-6 text-xs font-mono text-foreground/30">{report.size}</td>
                  <td className="px-8 py-6">
                    <div className="flex items-center justify-end gap-3 opacity-0 group-hover:opacity-100 transition-all translate-x-4 group-hover:translate-x-0">
                      <button className="p-2.5 bg-background border border-border rounded-xl text-primary hover:bg-primary hover:text-white transition-all shadow-sm">
                        <Download size={18} />
                      </button>
                      <button className="p-2.5 bg-background border border-border rounded-xl text-foreground/40 hover:text-foreground transition-all shadow-sm">
                        <MoreVertical size={18} />
                      </button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
        
        <div className="p-6 bg-surface/20 border-t border-border flex items-center justify-between">
          <p className="text-[10px] font-black text-foreground/30 uppercase tracking-widest">Showing 5 of 1,248 entries</p>
          <div className="flex gap-2">
            <button className="px-4 py-2 bg-background border border-border rounded-xl text-[10px] font-black uppercase tracking-widest opacity-50 cursor-not-allowed">Previous</button>
            <button className="px-4 py-2 bg-background border border-border rounded-xl text-[10px] font-black uppercase tracking-widest hover:bg-surface transition-colors">Next Page</button>
          </div>
        </div>
      </motion.div>
    </motion.div>
  );
};
